Remove error message due to access to ipmb_host when not installed
Mellanox/mlx-OpenIPMI pull request #60
Opened 2023-05-21 08:58 UTC by AdiFogel

ipmb_host drive is needed for BF to send IPMI commands over IPMB to the BMC. This is not needed for all types of images. In case the driver is not installed, there will be an error message because the set_emu_param is trying to load the driver. To prevent this error message, this commit adds a check if the driver is installed before trying to load it

2023-05-21 13:26 UTC, odrang requested changes
In the commit message:
- add description how this was tested
- change the signoff to your main (currently root)

2023-05-21 14:37 UTC, AdiFogel commented on lanserv/mellanox-bf/set_emu_param.sh
> +	if [ ! "$(lsmod | grep ipmb_host)" ] && modinfo ipmb_host; then
changed it to  check if the driver exist, modinfo will not work in case there is issue with loading the driver (such as modprobe -r)

2023-05-22 18:25 UTC, odrang commented
looks good to me

2023-05-23 07:31 UTC, AdiFogel commented
Hi @asmaamellanox ,
Can you please review?
Thanks,
Adi

2023-05-23 12:32 UTC, asmaamellanox commented on lanserv/mellanox-bf/set_emu_param.sh
> +# ipmb_host driver is not install in all images
typo: is not installed

2023-05-23 12:32 UTC, asmaamellanox commented on lanserv/mellanox-bf/set_emu_param.sh
> +
please remove extra line

2023-05-23 12:32 UTC, asmaamellanox commented on lanserv/mellanox-bf/set_emu_param.sh
> +                echo " ipmb host true"
please remove the echo. We dont want to print too many messages

2023-05-23 13:19 UTC, merged