Add fixed for QSFP temperature and EEPROM
Mellanox/mlx-OpenIPMI pull request #62
Opened 2023-05-29 09:46 UTC by AdiFogel

1. QSFP temperature - When one side of the cable was disconnected the link will be changed to down. In this case, if the second side has disconnected also, we would still see the temperature on the cable, because we have not detected the change. In this fix, in every set_emu_param.sh run, the script will do "mst cable add",
 to add or remove the cable if needed.
2. QSFP EEPROM - In case cables have been changed between the set_emu_param.sh cycle, we will not read the new EEPROM because it did not notice a change in the link.
 With this change, we will read it in any case that we have the cable.

Tested:
Removing the cable side by side

2023-05-29 09:47 UTC, AdiFogel commented
Hi @odrang and @asmaamellanox,

Please review

2023-05-29 17:09 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +	mst cable add > /dev/null 2>&1
add comment what the "mst cable add" perform

2023-05-29 17:09 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
>  # has changed.
wrong comment, please fix

2023-05-30 11:14 UTC, AdiFogel commented on lanserv/mellanox-bf/set_emu_param.sh
> +	mst cable add > /dev/null 2>&1
done

2023-05-30 11:14 UTC, AdiFogel commented on lanserv/mellanox-bf/set_emu_param.sh
>  # has changed.
done

2023-05-30 12:59 UTC, asmaamellanox requested changes
This is not going to work. I used to have "mst cable add" run every time the script runs and we had to change that behavior:
https://github.com/Mellanox/mlx-OpenIPMI/pull/17/commits/c0950782267098467a6d5e1e726aecbc088b8cfc

Please talk to the mft team to find a better solution

2023-06-11 08:18 UTC, AdiFogel commented
Hi @asmaamellanox  and @odrang,
The MR was updated and tested according to commit message.

Please review

2023-06-12 10:18 UTC, odrang commented
Hi Adi:
on the pull request:

3. mlxcables soon to be deprecated.
Solution:

What is the solution?

2023-06-12 10:45 UTC, AdiFogel commented
> Hi Adi: on the pull request:
> 
> 3. mlxcables soon to be deprecated.
>    Solution:
> 
> What is the solution?

From the commit message:
Solution:
1. On each loop of the set_emu script, if the port detected a connection, the
   temperature and EEPROM data will be updated
2. Using mlxlink command instead of mlxcables

2023-06-12 10:46 UTC, odrang requested changes

2023-06-12 10:46 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +	| tr -d "\n"  | perl -lpe '$_=pack"H*",$_' >  $EMU_PARAM_DIR/temp1
change the name temp1--> tmp (confusing with the temp which mean temperature)

2023-06-12 10:46 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +update_cables_info()
what is $1? add comment

2023-06-12 10:46 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +	update_cables_info $EMU_PARAM_DIR/eth_bdfs.txt
what about case of IB?
eth_bdfs.txt duplicated

2023-06-12 10:46 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +			func=$(echo $bdf | cut -f 1 -d " " | cut -f 2 -d ".")
add comments

2023-06-12 10:46 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +				echo 2 > $EMU_PARAM_DIR/p$func"_link"
do we need this or it is already handled in line 442?

2023-06-12 10:51 UTC, odrang commented
ok so in that case the alignment of the commit message is not clear ,should be:

3. mlxcables soon to be deprecated.
   Solution:
          - On each loop of the set_emu script, if the port detected a connection, the
          - temperature and EEPROM data will be updated
          - Using mlxlink command instead of mlxcables
4. Tests:
          - reboots on each cable state (plugged bot side, plugged one side and both
            sides), verify that temperature and EEPROM are set correctly.
          - Test case scenarios: while Linux is booting unplug the cable and plug it back.
            Right before reboot, unplug the cable, issue reboot, checked that is marked as
            unplugged, and plug back.

2023-06-12 13:04 UTC, AdiFogel commented on lanserv/mellanox-bf/set_emu_param.sh
> +update_cables_info()
added

2023-06-12 13:04 UTC, AdiFogel commented on lanserv/mellanox-bf/set_emu_param.sh
> +	update_cables_info $EMU_PARAM_DIR/eth_bdfs.txt
fixed

2023-06-12 13:04 UTC, AdiFogel commented on lanserv/mellanox-bf/set_emu_param.sh
> +			func=$(echo $bdf | cut -f 1 -d " " | cut -f 2 -d ".")
added

2023-06-12 16:26 UTC, odrang approved these changes
looks good

2023-06-15 18:31 UTC, asmaamellanox commented
Please view my comments from https://github.com/Mellanox/mlx-OpenIPMI/commit/1ee492f25f12efacb77dc4cd2916736556ee6cbb

regarding this change.

2023-06-15 18:32 UTC, asmaamellanox requested changes
please see my comments in:
https://github.com/Mellanox/mlx-OpenIPMI/commit/1ee492f25f12efacb77dc4cd2916736556ee6cbb

2023-06-20 14:54 UTC, asmaamellanox commented on lanserv/mellanox-bf/set_emu_param.sh
> +# $1 is $EMU_PARAM_DIR/eth_bdfs.txt or $EMU_PARAM_DIR/eth_bdfs.txt
not a descriptive comment. Please replace this by :
$1 is the full path of the ethernet or infiniband bdfs file.

2023-06-21 06:09 UTC, AdiFogel commented on lanserv/mellanox-bf/set_emu_param.sh
> +# $1 is $EMU_PARAM_DIR/eth_bdfs.txt or $EMU_PARAM_DIR/eth_bdfs.txt
done

2023-06-21 13:40 UTC, asmaamellanox approved these changes

2023-06-21 13:47 UTC, merged