Adjust script to match IB interface
Mellanox/mlx-OpenIPMI pull request #71
Opened 2023-10-15 17:59 UTC by AlonLapidus

Allow a more consistent output with 'ip' command instead of 'ifconfig'.

Tested:

//BF3, LinkType is Ethernet:

```
root@dpu-bmc:~# busctl introspect xyz.openbmc_project.Settings.dpu_eth /xyz/openbmc_project/network/host0/eth0
NAME                                          TYPE      SIGNATURE RESULT/VALUE                             FLAGS
org.freedesktop.DBus.Introspectable           interface -         -                                        -
.Introspect                                   method    -         s                                        -
org.freedesktop.DBus.Peer                     interface -         -                                        -
.GetMachineId                                 method    -         s                                        -
.Ping                                         method    -         -                                        -
org.freedesktop.DBus.Properties               interface -         -                                        -
.Get                                          method    ss        v                                        -
.GetAll                                       method    s         a{sv}                                    -
.Set                                          method    ssv       -                                        -
.PropertiesChanged                            signal    sa{sv}as  -                                        -
xyz.openbmc_project.Network.EthernetInterface interface -         -                                        -
.AutoNeg                                      property  b         false                                    emits-change
.DHCPEnabled                                  property  s         "xyz.openbmc_project.Network.Ethernet... emits-change writable
.DefaultGateway                               property  s         ""                                       emits-change writable
.DefaultGateway6                              property  s         ""                                       emits-change writable
.DomainName                                   property  as        0                                        emits-change writable
.IPv6AcceptRA                                 property  b         false                                    emits-change writable
.InterfaceName                                property  s         "enp3s0f0s0"                             const
.LinkLocalAutoConf                            property  s         "xyz.openbmc_project.Network.Ethernet... emits-change writable
.LinkUp                                       property  b         true                                     emits-change
.MTU                                          property  u         1500                                     emits-change writable
.NICEnabled                                   property  b         false                                    emits-change writable
.NTPServers                                   property  as        0                                        emits-change writable
.Nameservers                                  property  as        0                                        emits-change writable
.Speed                                        property  u         200000                                   emits-change
.StaticNTPServers                             property  as        0                                        emits-change writable
.StaticNameServers                            property  as        0                                        emits-change writable
xyz.openbmc_project.Network.LinkType          interface -         -                                        -
.LinkType                                     property  s         "Ethernet"                               emits-change
.PossibleLinks                                property  as        2 "Ethernet" "InfiniBand"                emits-change writable
xyz.openbmc_project.Network.MACAddress        interface -         -                                        -
.MACAddress                                   property  s         "02:46:c6:47:7c:3e"                      emits-change writable
```

// LinkType InfiniBand:

```
root@dpu-bmc:~# busctl introspect xyz.openbmc_project.Settings.dpu_eth /xyz/openbmc_project/network/host0/eth1
NAME                                          TYPE      SIGNATURE RESULT/VALUE                             FLAGS
org.freedesktop.DBus.Introspectable           interface -         -                                        -
.Introspect                                   method    -         s                                        -
org.freedesktop.DBus.Peer                     interface -         -                                        -
.GetMachineId                                 method    -         s                                        -
.Ping                                         method    -         -                                        -
org.freedesktop.DBus.Properties               interface -         -                                        -
.Get                                          method    ss        v                                        -
.GetAll                                       method    s         a{sv}                                    -
.Set                                          method    ssv       -                                        -
.PropertiesChanged                            signal    sa{sv}as  -                                        -
xyz.openbmc_project.Network.EthernetInterface interface -         -                                        -
.AutoNeg                                      property  b         false                                    emits-change
.DHCPEnabled                                  property  s         "xyz.openbmc_project.Network.Ethernet... emits-change writable
.DefaultGateway                               property  s         ""                                       emits-change writable
.DefaultGateway6                              property  s         ""                                       emits-change writable
.DomainName                                   property  as        0                                        emits-change writable
.IPv6AcceptRA                                 property  b         false                                    emits-change writable
.InterfaceName                                property  s         "ib1"                                    const
.LinkLocalAutoConf                            property  s         "xyz.openbmc_project.Network.Ethernet... emits-change writable
.LinkUp                                       property  b         false                                    emits-change
.MTU                                          property  u         4092                                     emits-change writable
.NICEnabled                                   property  b         false                                    emits-change writable
.NTPServers                                   property  as        0                                        emits-change writable
.Nameservers                                  property  as        0                                        emits-change writable
.Speed                                        property  u         0                                        emits-change
.StaticNTPServers                             property  as        0                                        emits-change writable
.StaticNameServers                            property  as        0                                        emits-change writable
xyz.openbmc_project.Network.LinkType          interface -         -                                        -
.LinkType                                     property  s         "InfiniBand"                             emits-change
.PossibleLinks                                property  as        2 "Ethernet" "InfiniBand"                emits-change writable
xyz.open [...]

2023-10-15 18:03 UTC, AlonLapidus commented
Hi @odrang, @AdiFogel, bpeled@nvidia.com, 
Please review, thanks.

2023-10-26 15:31 UTC, odrang requested changes

2023-10-26 15:31 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +
I don't understand the logic why do we need both if? 
Lets review Sunday

2023-10-30 12:06 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +	if lspci -n | grep 0200 | cut -f 1 -d " " | grep -q .
@AlonLapidus - are you sure this is working? have you tested? what if we have 2 ports?

2023-10-30 12:57 UTC, AlonLapidus commented on lanserv/mellanox-bf/set_emu_param.sh
> +			if $2 && [ -z "$eth" ]; then
no, $2 will be false in this case and the info for eth1 will be 'NA'

2023-10-30 12:58 UTC, AlonLapidus commented on lanserv/mellanox-bf/set_emu_param.sh
>  if [ $(( $curr_time % 60 )) -eq 0 ]; then
added

2023-10-30 12:59 UTC, AlonLapidus commented on lanserv/mellanox-bf/set_emu_param.sh
> +	if lspci -n | grep 0200 | cut -f 1 -d " " | grep -q .
Yes, tested on dual port and single port. For single it will always be false, for dual only if one port is Eth and the other is IB

2023-10-31 16:54 UTC, merged