Improve the IPMB connection between BMC and DPU
Mellanox/mlx-OpenIPMI pull request #75
Opened 2023-11-15 07:57 UTC by qiansunn

This feature is to improve the IPMB connection time between BMC and DPU. When BMC is booting up, it sends specific IPMI OEM command to DPU as a notification, so the DPU can know the BMC is ready, and load ipmb-host driver. This feature is only for Bluefield-3 currently.

1. Remove the 150s delay for all Bluefield-3. Normally, BMC is faster than DPU on BF3 to start IPMB service, and can handle the message from DPU, so the handshake in ipmb_host can be successful.
2. New IPMI OEM command is implemented in the OpenIPMI OEM handler. This command handler is used to receive the notification from BMC to DPU. When OEM handler receives this command from BMC, it will check the status of the ipmb-host driver, and reload the ipmb-host if needed.

RM: 3631288

2023-11-15 08:27 UTC, AdiFogel commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> -static void ipmi_get_system_time(lmc_data_t    *mc,
Need to make sure that we adjust the this command from the BMC side.

2023-11-15 13:24 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> -static void ipmi_get_system_time(lmc_data_t    *mc,
I created a MR to change this command on BMC side: https://gitlab-master.nvidia.com/dgx/bmc/openbmc/-/merge_requests/7287
It's also waiting for review. Please help take a look.

2023-11-15 20:42 UTC, asmaamellanox requested changes

2023-11-15 20:42 UTC, asmaamellanox commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        rdata[0] = 0x0;
This is redundant with line 92.  I would suggest to move line 92-93 inside GET_SYSTEM_TIME_CMD

2023-11-15 20:42 UTC, asmaamellanox commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        if (init_module(module, module_size, IPMB_HOST_PARAM) != 0) {
are you sure this works?
you need both these commands to make it work:
modprobe ipmb_host slave_add=0x10
echo ipmb-host 0x1011 > $I2C_NEW_DEV

did you test any ipmitool commands?

2023-11-19 13:22 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        rdata[0] = 0x0;
Done

2023-11-19 13:22 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        /* Load ipmi_host driver */
Done

2023-11-19 13:22 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        int len = strlen(path_buffer);
Done

2023-11-19 13:23 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        /* If flag is exist, driver don't need to be loaded again */
Done

2023-11-19 13:35 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        if (init_module(module, module_size, IPMB_HOST_PARAM) != 0) {
I updated the code to add "echo ipmb-host 0x1011 > $I2C_NEW_DEV".
Yes, I tested it. Actually, it can work without second command in this handler.
"echo ipmb-host 0x1011 > $I2C_NEW_DEV" will be ran in set_emu_param.sh after the DPU OS started. Even If the handshake with BMC not successful (BMC is not ready), this ipmb-host is still registered as i2c_new_device. When BMC is ready, it can work by just remove and initialize the driver.

2023-11-19 14:57 UTC, qiansunn commented on lanserv/mellanox-bf/set_emu_param.sh
> +bfversion=$(bfhcafw mcra 0xf0014.0:16)
I updated the code to add this Platform ID in environment file: /etc/ipmi/progconf, as an argument to the set_emu_param.sh

2023-11-19 15:03 UTC, qiansunn commented on lanserv/mellanox-bf/set_emu_param.sh
> +	# Roy-B doesn't need the delay of loading the driver.
I'm not sure change the output of bffamily will affect other components in dpu or not. If other parts relay on bffamily output, they could be broken. Currently I just modified the environment file "progconf" of mlx_ipmid service and set_emu_param service, to pass the Platform ID as an environment variable, so it won't consume the CPU time. Is it OK in your opinion?

2023-11-20 13:06 UTC, qiansunn commented on lanserv/mellanox-bf/set_emu_param.sh
> +	# Roy-B doesn't need the delay of loading the driver.
I removed this part of the code.

2023-11-20 13:44 UTC, asmaamellanox commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        if (init_module(module, module_size, IPMB_HOST_PARAM) != 0) {
ack

2023-11-20 13:54 UTC, asmaamellanox commented
Hi Qian,

Why are you applying these changes now for both BF2 and BF3? I mean I am ok with this change but just wanted to make sure it is your intention.

2023-11-20 16:17 UTC, qiansunn commented
> Hi Qian,
> 
> Why are you applying these changes now for both BF2 and BF3? I mean I am ok with this change but just wanted to make sure it is your intention.

We saw this issue on BF2: https://redmine.mellanox.com/issues/3647483. It should be also related to the delay. So, we should apply the same design that you are doing in BF2 as well, in case that the driver was not loaded.

2023-11-20 16:46 UTC, asmaamellanox approved these changes

2023-11-21 08:16 UTC, qiansunn commented on lanserv/mellanox-bf/set_emu_param.sh
> +bfversion=$(bfhcafw mcra 0xf0014.0:16)
Hi Asmma, just update the code to apply the same design on BF2, but keep the delay on BF2. This is because BMC is always slower than DPU to be ready on BF2. If we remove the delay and user haven't updated the BMC to the latest version, it could cause the ipmb connection issue.

2023-11-21 08:17 UTC, AdiFogel commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +    /* assume mod_len <= sizeof(buffer) */
why you are assuming and not checking?

2023-11-21 08:32 UTC, AdiFogel commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        module_size = st.st_size;
Why are you not using the module directly? why do you need this temporary buffer (path_buffer)

2023-11-21 13:00 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +        module_size = st.st_size;
This is because the path of the driver file is different on different Linux distribution. So, we need get the path from the output of modinfo and store it. Then open the file from the path.

2023-11-21 13:57 UTC, asmaamellanox approved these changes

2023-11-21 14:19 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +    /* assume mod_len <= sizeof(buffer) */
Done

2023-11-21 14:20 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +    case LOAD_IPMB_DRIVER_CMD:
Done

2023-11-22 08:56 UTC, AdiFogel approved these changes

2023-11-22 10:12 UTC, odrang commented on lanserv/mellanox-bf/mlx_ipmid.service
> +ExecStartPre=/bin/bash -c '/usr/bin/mlx_ipmid_init.sh ${BF_FAMILY} ${SUPPORT_IPMB} ${OOB_IP} ${EXTERNAL_DDR} ${LOOP_PERIOD} ${BF_VERSION}'
why are we dependent on the BF_VERSION?

2023-11-22 10:12 UTC, odrang commented on lanserv/mellanox-bf/set_emu_param.sh
> +		   ([ "$bffamily" = "Roy" ] && [ "$bf_version" = $BF2_PLATFORM_ID ]); then
PRIS is BF1 what is the expected behavior in this case?
also please add comment to explain this in the code.

2023-11-22 12:10 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +    if (module_is_loaded("ipmb_host") == 1) {
The name of the module file(.ko) is different on same system. But the module name "ipmb_host" in /proc/modules are the same on all system. In the code, we use the name "ipmb_host" under /proc/modules to check if the module is loaded or not.

2023-11-22 13:46 UTC, qiansunn commented on lanserv/mellanox-bf/mlx_ipmid.service
> +ExecStartPre=/bin/bash -c '/usr/bin/mlx_ipmid_init.sh ${BF_FAMILY} ${SUPPORT_IPMB} ${OOB_IP} ${EXTERNAL_DDR} ${LOOP_PERIOD} ${BF_VERSION}'
This is because currently I want to remove the delay on BF3 but keep the delay on BF2&BF1. 
1. The BMC is slower than DPU to be ready on BF2&BF1.
2. The BMC is faster than DPU to be ready on BF3.

If we remove the delay on BF2&BF1, and customer just update the BFB image without BMC FW, their ipmb will be failed after power cycle the board, until they use the latest BMC FW which included the changes. So currently I suggest keeping the delay on BF2&BF1 until customer ask us to remove the delay and updated the BMC.

On BF2&BF1, I assume that we are solving the issue that IPMB could not working because BMC booting slower and the delay is not enough. So there is no need to remove the delay for them.

The BF_VERSION is used to distinguish the "Roy" and "Roy-B". BF_FAMILY(/usr/bin/bffamily) output the same name as "Roy" for the BF3 and BF2. So we need the BF_VERSION to determine it is "Roy" or "Roy-B". I didn't change the output of bffamily to distinguish "Roy" and "Roy-B", this is because bffamily is not a part of mlx-OpenIPMI and I'm not sure if change the output of bffamily will affect other components in DPU or not.

2023-11-22 14:19 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +static int load_ipmb_host_driver()
1. The ipmb_host is dependent on "ipmi_msghandler", and the module "ipmb_dev_int" is also dependent on "ipmi_msghandler". "ipmb_dev_int" is used to receive IPMI message from BMC. That means if "ipmi_msghandler" is not ready, the "ipmb_dev_int" is not initialized and can't receive message from BMC, so the handler won't be called to load "ipmb_host".
2. Using init_module give us more debuggability because it can save the errno. This function is faster than call the application. And I hope to avoid more shell command in C code.

2023-11-22 14:28 UTC, qiansunn commented on lanserv/mellanox-bf/mellanox_bf_mod.c
> +static void handle_oem_command(lmc_data_t    *mc,
The function is a general function to handle all OEM commands with same IANA number. And we check the different function number in it. Otherwise, we can't distinguish different function numbers with the same function. This design is referred to the Marvell's OEM Module, it has a similar function: https://github.com/Mellanox/mlx-OpenIPMI/blob/main/lanserv/marvell-bmc/marvell_mod.c#L3127

2023-11-22 14:43 UTC, qiansunn commented on lanserv/mellanox-bf/set_emu_param.sh
> +		   ([ "$bffamily" = "Roy" ] && [ "$bf_version" = $BF2_PLATFORM_ID ]); then
We keep the delay for BF2&BF1, as customer doesn't ask us to remove the delay for them. Currently we are facing the issue is IPMB could not working because BMC booting slower, and the delay is not enough.
Remove the delay won't help solve the issue. Besides, if user just update the BFB image without BMC FW, their IPMB handshake from DPU to BMC will be failed. They need to update both BFB and BMC FW to solve it.

2023-11-23 16:06 UTC, merged